name: Bug Report
description: ' Use this template if you''re running into bugs or other issues. '
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: version
    attributes:
      label: Version information
      description: >-
        Please provide the exact version of the mod you are using. Every part of
        the version is important! If you do not know what version you are using,
        look at the file name in your `mods` folder.
      placeholder: 'Example: 2.3.0+mc1.17'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'Example: I should have to hold down the ''drop'' button to drop this item.'
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What did actually happen?
      placeholder: 'Example: The item drops instantly.'
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: >-
        Provide information on how to reproduce this bug. You can either
        fill this section in like the example below or do something else just
        make sure your instructions are minimal and clear, as other people will
        need to be able to replicate your issue.
      placeholder: |
        Example:
        1. Select an item
        2. Press your drop button
        3. The item drops instantly
    validations:
      required: true
  - type: input
    id: java
    attributes:
      label: Java version
      placeholder: 'Example: Java 16'
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >-
        Provide a list of any other mods you are using, along with their
        respective versions. If you have any screenshots, videos, or other
        information that you feel is necessary to explain the issue, feel free
        to attach them here.
