name: Feature Request
description: ' Use this template if you want to request a feature for this project. '
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for your requested feature.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: related_problem
    attributes:
      label: Related problem
      description: Please provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Suggested solution
      description: Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternate_solutions
    attributes:
      label: Alternative solutions
      description: Please provide a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the feature request here.
